// react-frontend/src/components/SignUp.tsx
import React, { FormEvent, useState } from 'react';
import { UserType } from '../types';

const signUpUser = async (user: UserType) => {
  const response = await fetch('http://localhost:8080/auth/sign-up', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(user),
  });

  const status = response.status;
  const data = await response.json();
  return { status, data };
};

const SignUp: React.FC = () => {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [isRegistered, setIsRegistered] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();

    setIsRegistered(false);
    setError(null);

    const { status, data } = await signUpUser({
      username,
      password,
    });

    if (status >= 400) {
      setError(data.message);
    } else {
      setIsRegistered(true);
    }
    setUsername('');
    setPassword('');
  };

  return (
    <div className="signUp-wrapper">
      <h2>Sign Up</h2>
      <form>
        <label>
          <p>Create Username</p>
          <input
            type="text"
            onChange={(e) => setUsername(e.target.value)}
            value={username}
          />
        </label>
        <label>
          <p>Create Password</p>
          <input
            type="password"
            onChange={(e) => setPassword(e.target.value)}
            value={password}
          />
        </label>
        <div>
          <button
            className="login-signup__button"
            type="submit"
            onClick={(e) => handleSubmit(e)}
          >
            Sign Up
          </button>
          {isRegistered && (
            <p className="text-success">You Are Registered Successfully</p>
          )}
          {error && <p className="text-error">{error}</p>}
        </div>
      </form>
    </div>
  );
};

export default SignUp;

// vue-frontend/src/components/SignUp.vue
<script setup lang="ts">
import { ref } from 'vue'
import { signUp } from '@/api'
import AuthField from '@/components/AuthField.vue'
import AuthSubmitButton from '@/components/AuthSubmitButton.vue'

const username = ref<string>('')
const password = ref<string>('')
const isRegistered = ref<boolean>(false)
const error = ref<string | null>(null)

const handleSubmit = async () => {
  isRegistered.value = false
  error.value = null

  const response = await signUp({
    username: username.value,
    password: password.value
  })

  const data = await response.json()
  if (response.ok) {
    isRegistered.value = true
  } else {
    error.value = data.message
  }

  username.value = ''
  password.value = ''
}
</script>

<template>
  <div class="sign-up__container">
    <h2>Sign Up</h2>
    <form @submit.prevent="handleSubmit">
      <AuthField id="sign-up__username" v-model="username" label="Create Username" />
      <AuthField id="sign-up__password" v-model="password" label="Create Password" />
      <div>
        <AuthSubmitButton label="Sign Up" />
        <p v-if="isRegistered" class="text-success">You Are Registered Successfully</p>
        <p v-if="error" class="text-error">{{ error }}</p>
      </div>
    </form>
  </div>
</template>

<style scoped>
.sign-up__container {
  display: flex;
  align-items: center;
  flex-direction: column;
  border-top: #000 solid 2px;
  padding-top: 30px;
  width: 80%;
}
</style>
